# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2

multi-ecosystem-groups:
  main:
    schedule:
      interval: "daily"
    target-branch: "main"

updates:
  - package-ecosystem: "devcontainers"
    multi-ecosystem-group: "main"
    directory: "/"
    patterns:
      - "*"

  - package-ecosystem: "github-actions"
    multi-ecosystem-group: "main"
    directory: "/"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    multi-ecosystem-group: "main"
    directory: "/"
    patterns:
      - "*"

  - package-ecosystem: "cargo"
    multi-ecosystem-group: "main"
    directory: "/"
    patterns:
      - "*"
